### ISSUE TITLE
Problem with wording in Figure 7D

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/EnvMutationalShiftsPaper#19]
@jbloom: I was looking at some of the edits you made and found a problem with the wording in the caption for Figure 7D. It says "crystallographically" resolved sites a few times, but the 5VN3 structure was determined using cryoEM. So, a more accurate wording would probably be "structurally" resolved, or something like that.

I raised this issue to as a reminder for one of us to address this before submitting. I'm happy to do it now if it wouldn't conflict with your revisions.

**Comment by jbloom** [comment]
@haddox: Yes, go ahead and change these to "structurally resolved" now.

**Comment by Haddox** [comment]
I just made these changes in commit 94eeaf0eafe4fa6dd7a4b767add21ef148e85340
